[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/raw/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  
